ci:
  engine:
    run:
      FROM:
        image: node:22-alpine
      steps:
        - COPY:
            src: package.json
            dest: /forge/package.json
        - WORKDIR: /forge
        - RUN: npm install --omit=dev
        - COPY:
            src: engine.js
            dest: /forge/engine.js
  pnpmfile:
    run:
      FROM:
        image: scratch
      steps:
        - COPY:
            src: templates/pnpmfile
            dest: /forge/templates/pnpmfile
  ts-ui:
    run:
      FROM:
        image: scratch
      steps:
        - COPY:
            src: templates/ts-ui
            dest: /forge/templates/ts-ui
  ts-lib:
    run:
      FROM:
        image: scratch
      steps:
        - COPY:
            src: templates/ts-lib
            dest: /forge/templates/ts-lib
  ts-executable:
    run:
      FROM:
        image: scratch
      steps:
        - COPY:
            src: templates/ts-executable
            dest: /forge/templates/ts-executable
